config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
    
    resources :libros do
        resources :reviews
    end

   root 'libros#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :libros
end

app/models/libro.rb
class Libro < ActiveRecord::Base
    belongs_to :user
    belongs_to :category
    has_many :reviews
    
    has_attached_file :libro_img, :styles => { :libro_index => "250x350>", :libro_show => "325x475>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :libro_img, :content_type => /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ActiveRecord::Base
   belongs_to :libro
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :libros
    has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
    before_action :find_libro, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]
    
    def index
        if params[:category].blank?
            @libros = Libro.all.order("created_at DESC")
        else
           @category_id = Category.find_by(name: params[:category]).id
            @libros = Libro.where(:category_id => @category_id).order("created_at DESC")    
        end
    end
    
    def show
        if @libro.reviews.blank?
			@average_review = 0
		else
			@average_review = @libro.reviews.average(:clasificacion).round(2)
		end  
    end
    
    def new
        @libro = current_user.libros.build
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end
    
    def create 
        @libro = current_user.libros.build(libro_params)
        @libro.category_id = params[:category_id]
        
        if @libro.save
            redirect_to root_path
        else
            render 'new'
        end
    end
    
    def edit
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end
    
    def update
        @libro.category_id = params[:category_id]
        if @libro.update(libro_params)
            redirect_to libro_path(@libro)
        else
            render 'edit'
        end 
    end
    
    def destroy
        @libro.destroy
        redirect_to root_path
    end
    
    private 
    
        def libro_params
            params.require(:libro).permit(:titulo, :descripcion, :autor, :category_id, :libro_img)
        end
    
        def find_libro
            @libro = Libro.find(params[:id]) 
        end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_libro
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.libro_id = @libro.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to libro_path(@libro)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to libro_path(@libro)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to libro_path(@libro)
	end

	private

		def review_params
			params.require(:review).permit(:clasificacion, :comentario)
		end

		def find_libro
			@libro = Libro.find(params[:libro_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Libros1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default" >
        <div class="container">
        
            <div class="navbar-header">
                <%= link_to "Libros", root_path, class: "navbar-brand" %>
            </div>
            
            <ul class="nav navbar-nav">
                <li><%= link_to "Registrarse", new_user_registration_path %></li>
                <% if user_signed_in? %>
                    <li><%= link_to "Cerrar Secion", destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to "Iniciar Secion", new_user_session_path %></li>
                <% end %>
            </ul>
            
            <ul class="nav navbar-nav navbar-right">
                
                
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categorias <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %> 
                        <li class="<%= 'active' if params[:category] == category.name %>" >
                            <%= link_to category.name, libros_path(category: category.name), class: "link" %>
                        </li>
                        <% end %>
                    </ul>
                </li>
                
                
                <% if user_signed_in? %>
                <li><%= link_to "Agregar Libro", new_libro_path %></li>
                <% end %>
            </ul>
            
        </div>
    
    </nav>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    
    <div class="container">
    <%= yield %>
    </div>
</body>
</html>

app/views/libros/_form.html.erb
<%= simple_form_for @libro, :html => { :miltipart => true } do |f| %>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Categorias") %>
    <%= f.file_field :libro_img %>
    <%= f.input :titulo, label: "Titulo del Libro" %>
    <%= f.input :descripcion %>
    <%= f.input :autor %>
    <%= f.button :submit %>
<% end %>

app/views/libros/edit.html.erb
<h1>Editar Libro</h1>

<%= simple_form_for @libro, :html => { :miltipart => true } do |f| %>
    <%= f.select :category_id, @categories %>
    <%= f.file_field :libro_img %>
    <%= f.input :titulo, label: "Titulo del Libro" %>
    <%= f.input :descripcion %>
    <%= f.input :autor %>
    <%= f.button :submit %>
<% end %>

app/views/libros/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @libros.count == 0 %>

    <h1>No hay Libros en esta Categoria</h1>
<% else %>

    <div class="row">

        <% @libros.each do |libro| %>
        
            <div class="col-md-3">
                <a href="/libros/ <%= libro.id %>">
                    <%= image_tag libro.libro_img.url(:libro_index), class: "libro" %>
                </a>
            </div>
        <% end %>

    </div>
    
<% end %>


app/views/libros/new.html.erb
<h1> Libro Nuevo</h1>

<%= render 'form' %>

app/views/libros/show.html.erb
<div class="row">

	<div class="col-md-4">

		<%= image_tag @libro.libro_img.url(:libro_show), class: "libro-show" %>

	</div>

	<div class="col-md-8">

		<div class="libro-info">

			<h2 class="libro-title"><%= @libro.titulo %></h2>
			<h3 class="libro-autor"><span>Por: </span> <%= @libro.autor %></h3>
			<h2 class="avg-clasificacion">Promedio de Clasificacion</h2>
			<div class="average-review-clasificacion" data-score=<%= @average_review %>></div>
			<span class="number-of-reviews">Basado en <%= @libro.reviews.count %> reviews</span>
			<p class="libro-desc"><%= @libro.descripcion %></p>

		</div>
	</div>


</div>

<div class="row">

	<div class="col-md-4">

		<div class="reviews">

			<!-- Where the reviews/ratings will go -->
			<h1>Calificaciones</h1>
			<%= render @libro.reviews %>

			<div>
				<%= link_to "Agregar Calificacion", new_libro_review_path(@libro), class: "btn-custom" %>
			</div>

		</div>	

	</div>

</div>

<div class="links btn-group">

	<%= link_to "Atras", root_path, class: "btn btn-custom" %>

	<% if user_signed_in? %>

		<% if @libro.user_id == current_user.id %>

			<%= link_to "Editar", edit_libro_path(@libro), class: "btn btn-custom" %>
			<%= link_to "Eliminar", libro_path(@libro), method: :delete, data: { confirm: "Estas Seguro?" }, class: "btn btn-custom" %>

		<% end %>

	<% end %>	

</div>	


<script>
	$('.review-clasificacion').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>


<script>
	$('.average-review-clasificacion').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

app/views/reviews/_form.html.erb
<%= simple_form_for([@libro, @libro.reviews.build]) do |f| %>
	<div id="clasificacion-form">
		<label>Clasificacion</label>
	</div>
	<%= f.input :comentario %>
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

<script>
	$('#clasificacion-form').raty({
		path: '/assets/',
		scoreName: 'review[clasificacion]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">

	<div class="review-clasificacion" data-score="<%= review.clasificacion %>"></div>
	<p class="review-comentario"><%= review.comentario %></p>


	<% if user_signed_in? %>

		<% if review.user_id == current_user.id %>

			<div class="links btn-group">

				<%= link_to "Editar", edit_libro_review_path(review.libro, review), class: "btn btn-custom" %>
				<%= link_to "Eliminar", libro_review_path(review.libro, review), method: :delete, data: { confirm: "Estas seguro ?" }, class: "btn btn-custom" %>

			</div>
		
		<% end %>	

	<% end %>

</div>		

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-review-form">

		<h1>Editar</h1>

		<%= simple_form_for([@libro, @review]) do |f| %>
			<div id="clasificacion-form">
				<label>Clasificacion</label>
			</div>
			<%= f.input :comentario %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>	

	</div>

</div>

<script>
	$('#clasificacion-form').raty({
		path: '/assets/',
		scoreName: 'review[clasificacion]'
	});
</script>

app/views/reviews/new.html.erb
<h1> Nueva Clasificacion </h1>

<%= render 'form' %>